# автоматически масштабирую количество подов на основе нагрузки по AverageValue CPU
# приложение не должно есть больше 100m по ТЗ, добавил 50m чтобы избежать лишнего масштабирования
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin-hpa
  namespace: httpbin-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpbin
  minReplicas: 5
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: "150m"
---
# не даю "убить" больше одного пода, чтобы было не меньше 4 на случай "осушения" ноды
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: httpbin-pdb
  namespace: httpbin-test
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: httpbin